'use strict';

module.exports = {

  questions: {

    tq_age: {
      id: 'tq_age',
      text: { english: 'How old is the animal?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'free_text',
      scoringQuestion: false,
      conditional: null,
    },
    tq_breed: {
      id: 'tq_breed',
      text: { english: 'What breed is the animal?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'free_text',
      scoringQuestion: false,
      conditional: null,
    },
    tq_reproduced: {
      id: 'tq_reproduced',
      text: { english: 'Has this animal ever given birth or reproduced?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_eating: {
      id: 'tq_eating',
      text: { english: 'How is the animal eating?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'multiple_choice',
      options: ['not_eating', 'eats_less', 'normal'],
      scoringQuestion: true,
      conditional: null,
    },
    tq_duration: {
      id: 'tq_duration',
      text: { english: 'How long has the animal been sick?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'free_text',
      scoringQuestion: false,
      conditional: null,
    },
    tq_water: {
      id: 'tq_water',
      text: { english: 'Is the animal drinking water?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_urine: {
      id: 'tq_urine',
      text: { english: 'Is the animal urinating?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: { question: 'tq_water', answer: 'yes' },
    },
    tq_urine_color: {
      id: 'tq_urine_color',
      text: { english: 'What colour is the urine?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'multiple_choice',
      options: ['bloody', 'very_dark', 'colourless', 'normal'],
      scoringQuestion: true,
      conditional: { question: 'tq_urine', answer: 'yes' },
    },
    tq_standing: {
      id: 'tq_standing',
      text: { english: 'Can the animal stand up on its own?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_getup: {
      id: 'tq_getup',
      text: { english: 'Can the animal get up if you help it?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: { question: 'tq_standing', answer: 'no' },
    },
    tq_lying_duration: {
      id: 'tq_lying_duration',
      text: { english: 'How long has it been unable to get up?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'free_text',
      scoringQuestion: false,
      conditional: { question: 'tq_getup', answer: 'no' },
    },
    tq_walking: {
      id: 'tq_walking',
      text: { english: 'Can the animal walk normally?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_walk_type: {
      id: 'tq_walk_type',
      text: { english: 'How is the animal moving?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'multiple_choice',
      options: ['circles', 'stumbling', 'not_walking', 'straight'],
      scoringQuestion: true,
      conditional: { question: 'tq_walking', answer: 'no' },
    },
    tq_limping: {
      id: 'tq_limping',
      text: { english: 'Is the animal limping?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: { question: 'tq_walking', answer: 'no' },
    },
    tq_cough: {
      id: 'tq_cough',
      text: { english: 'Is the animal coughing?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_diarrhea: {
      id: 'tq_diarrhea',
      text: { english: 'Does the animal have diarrhea?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_stool: {
      id: 'tq_stool',
      text: { english: 'What does the stool look like?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'multiple_choice',
      options: ['bloody', 'watery', 'hard', 'normal'],
      scoringQuestion: true,
      conditional: { question: 'tq_diarrhea', answer: 'yes' },
    },
    tq_swollen: {
      id: 'tq_swollen',
      text: { english: 'Is any part of the body swollen?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_swollen_part: {
      id: 'tq_swollen_part',
      text: { english: 'Which part of the body is swollen?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'free_text',
      scoringQuestion: false,
      conditional: { question: 'tq_swollen', answer: 'yes' },
    },
    tq_lymph: {
      id: 'tq_lymph',
      text: { english: 'Are the lymph nodes (glands on neck or legs) swollen?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_wounds: {
      id: 'tq_wounds',
      text: { english: 'Does the animal have any wounds or sores?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_wound_part: {
      id: 'tq_wound_part',
      text: { english: 'Where are the wounds or sores?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'free_text',
      scoringQuestion: false,
      conditional: { question: 'tq_wounds', answer: 'yes' },
    },
    tq_secretions: {
      id: 'tq_secretions',
      text: { english: 'Does the animal have any discharge or secretions?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_secretion_type: {
      id: 'tq_secretion_type',
      text: { english: 'What type of discharge?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'multiple_choice',
      options: ['blood', 'pus', 'froth', 'mucus'],
      scoringQuestion: true,
      conditional: { question: 'tq_secretions', answer: 'yes' },
    },
    tq_secretion_from: {
      id: 'tq_secretion_from',
      text: { english: 'Where is the discharge coming from?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'free_text',
      scoringQuestion: false,
      conditional: { question: 'tq_secretions', answer: 'yes' },
    },
    tq_skin: {
      id: 'tq_skin',
      text: { english: 'Does the animal have skin problems (rash, patches or lesions)?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_skin_desc: {
      id: 'tq_skin_desc',
      text: { english: 'Describe the skin problem.', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'free_text',
      scoringQuestion: false,
      conditional: { question: 'tq_skin', answer: 'yes' },
    },
    tq_vomiting: {
      id: 'tq_vomiting',
      text: { english: 'Is the animal vomiting?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_sudden_death: {
      id: 'tq_sudden_death',
      text: { english: 'Have any animals in the group died suddenly?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_noise: {
      id: 'tq_noise',
      text: { english: 'Is the animal making unusual sounds or crying out?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_sight: {
      id: 'tq_sight',
      text: { english: 'Does the animal seem to have problems with its eyesight?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_hair_loss: {
      id: 'tq_hair_loss',
      text: { english: 'Is the animal losing hair or wool?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_vaccination: {
      id: 'tq_vaccination',
      text: { english: 'What vaccinations has the animal received?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'free_text',
      scoringQuestion: false,
      conditional: null,
    },

    tq_udder: {
      id: 'tq_udder',
      text: { english: 'Is the udder swollen, hard or painful?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: null,
    },
    tq_milk: {
      id: 'tq_milk',
      text: { english: 'How is milk production?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'multiple_choice',
      options: ['stopped', 'different', 'less', 'normal'],
      scoringQuestion: true,
      conditional: null,
    },
    tq_reproduction: {
      id: 'tq_reproduction',
      text: { english: 'Has the animal reproduced successfully since the last time?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: true,
      conditional: { question: 'tq_reproduced', answer: 'yes' },
    },
    tq_repro_problem: {
      id: 'tq_repro_problem',
      text: { english: 'Describe the reproductive problem.', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'free_text',
      scoringQuestion: false,
      conditional: { question: 'tq_reproduction', answer: 'no' },
    },
    tq_eggs: {
      id: 'tq_eggs',
      text: { english: 'How is egg production?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'multiple_choice',
      options: ['stopped', 'less', 'normal'],
      scoringQuestion: true,
      conditional: null,
    },
    tq_feed: {
      id: 'tq_feed',
      text: { english: 'Is the animal getting adequate feed?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: false,
      conditional: null,
    },
    tq_shelter: {
      id: 'tq_shelter',
      text: { english: 'Does the animal have adequate shelter?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: false,
      conditional: null,
    },
    tq_ectoparasites: {
      id: 'tq_ectoparasites',
      text: { english: 'Does the animal have visible ticks, lice or mites?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: false,
      conditional: null,
    },
    tq_deworm: {
      id: 'tq_deworm',
      text: { english: 'Has the animal been dewormed in the last 3 months?', runyankole: '[PLACEHOLDER]', acholi: '[PLACEHOLDER]' },
      type: 'yes_no',
      scoringQuestion: false,
      conditional: null,
    },
  },

  universalFlow: [
    'tq_age',
    'tq_breed',
    'tq_reproduced',
    'tq_eating',
    'tq_duration',
    'tq_water',
    'tq_urine',
    'tq_urine_color',
    'tq_standing',
    'tq_getup',
    'tq_lying_duration',
    'tq_walking',
    'tq_walk_type',
    'tq_limping',
    'tq_cough',
    'tq_diarrhea',
    'tq_stool',
    'tq_swollen',
    'tq_swollen_part',
    'tq_lymph',
    'tq_wounds',
    'tq_wound_part',
    'tq_secretions',
    'tq_secretion_type',
    'tq_secretion_from',
    'tq_skin',
    'tq_skin_desc',
    'tq_vomiting',
    'tq_sudden_death',
    'tq_noise',
    'tq_sight',
    'tq_hair_loss',
    'tq_vaccination',
  ],

  speciesFlow: {
    cattle: [
      'tq_udder',
      'tq_milk',
      'tq_reproduction',
      'tq_repro_problem',
      'tq_feed',
      'tq_shelter',
      'tq_ectoparasites',
      'tq_deworm',
    ],
    poultry: [
      'tq_eggs',
      'tq_feed',
      'tq_shelter',
      'tq_ectoparasites',
      'tq_deworm',
    ],
    pigs: [
      'tq_feed',
      'tq_shelter',
      'tq_ectoparasites',
      'tq_deworm',
    ],
    rabbit: [
      'tq_feed',
      'tq_shelter',
      'tq_ectoparasites',
      'tq_deworm',
    ],
    goat: [
      'tq_udder',
      'tq_milk',
      'tq_reproduction',
      'tq_repro_problem',
      'tq_feed',
      'tq_shelter',
      'tq_ectoparasites',
      'tq_deworm',
    ],
    sheep: [
      'tq_reproduction',
      'tq_repro_problem',
      'tq_feed',
      'tq_shelter',
      'tq_ectoparasites',
      'tq_deworm',
    ],
    dog: [
      'tq_feed',
      'tq_shelter',
      'tq_ectoparasites',
      'tq_deworm',
    ],
  },

  diseases: {

    cattle: {
      Mastitis: {
        questions:  ['tq_udder', 'tq_milk', 'tq_secretions', 'tq_limping'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      Brucellosis: {
        questions:  ['tq_reproduction', 'tq_reproduced', 'tq_udder'],
        thresholds: { MEDIUM: 1, HIGH: 2 },
      },
      ECF: {
        questions:  ['tq_lymph', 'tq_eating', 'tq_cough', 'tq_swollen'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      FMD: {
        questions:  ['tq_limping', 'tq_secretions', 'tq_wounds', 'tq_milk', 'tq_vomiting'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
    },

    poultry: {
      'Avian Flu': {
        questions:  ['tq_sudden_death', 'tq_swollen', 'tq_eating', 'tq_diarrhea'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      Newcastle: {
        questions:  ['tq_cough', 'tq_walk_type', 'tq_eggs', 'tq_diarrhea'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      Coccidiosis: {
        questions:  ['tq_diarrhea', 'tq_stool', 'tq_eating', 'tq_water'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
    },

    pigs: {
      ASF: {
        questions:  ['tq_sudden_death', 'tq_skin', 'tq_standing', 'tq_diarrhea'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      PRRS: {
        questions:  ['tq_reproduced', 'tq_reproduction', 'tq_cough'],
        thresholds: { MEDIUM: 1, HIGH: 2 },
      },
      FMD: {
        questions:  ['tq_secretions', 'tq_limping', 'tq_wounds', 'tq_vomiting'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      Erysipelas: {
        questions:  ['tq_skin', 'tq_limping', 'tq_sudden_death'],
        thresholds: { MEDIUM: 1, HIGH: 2 },
      },
      'Swine Dysentery': {
        questions:  ['tq_diarrhea', 'tq_stool', 'tq_standing'],
        thresholds: { MEDIUM: 1, HIGH: 2 },
      },
      Ascariasis: {
        questions:  ['tq_cough', 'tq_swollen', 'tq_eating'],
        thresholds: { MEDIUM: 1, HIGH: 2 },
      },
    },

    rabbit: {
      Coccidiosis: {
        questions:  ['tq_diarrhea', 'tq_swollen', 'tq_eating', 'tq_standing'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      Snuffles: {
        questions:  ['tq_secretions', 'tq_secretion_type'],
        thresholds: { MEDIUM: 1, HIGH: 2 },
      },
      Myxomatosis: {
        questions:  ['tq_swollen', 'tq_lymph', 'tq_skin', 'tq_eating'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      'Ear Mites': {
        questions:  ['tq_noise', 'tq_skin', 'tq_sight'],
        thresholds: { MEDIUM: 1, HIGH: 2 },
      },
      RHD: {
        questions:  ['tq_sudden_death', 'tq_secretions'],
        thresholds: { MEDIUM: 1, HIGH: 2 },
      },
      'GI Stasis': {
        questions:  ['tq_eating', 'tq_diarrhea', 'tq_swollen', 'tq_vomiting'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
    },

    goat: {
      Helminthosis: {
        questions:  ['tq_eating', 'tq_standing', 'tq_diarrhea', 'tq_swollen', 'tq_hair_loss'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      FMD: {
        questions:  ['tq_limping', 'tq_wounds', 'tq_secretions', 'tq_milk'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      Brucellosis: {
        questions:  ['tq_reproduction', 'tq_udder'],
        thresholds: { MEDIUM: 1, HIGH: 2 },
      },
      Clostridial: {
        questions:  ['tq_sudden_death', 'tq_standing', 'tq_walking', 'tq_vomiting'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
    },

    sheep: {
      Helminthosis: {
        questions:  ['tq_eating', 'tq_standing', 'tq_diarrhea', 'tq_swollen', 'tq_hair_loss'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      FMD: {
        questions:  ['tq_limping', 'tq_wounds', 'tq_secretions'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      Brucellosis: {
        questions:  ['tq_reproduction', 'tq_reproduced'],
        thresholds: { MEDIUM: 1, HIGH: 2 },
      },
      Clostridial: {
        questions:  ['tq_sudden_death', 'tq_standing', 'tq_walking', 'tq_vomiting'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
    },

    dog: {
      Rabies: {
        questions:  ['tq_noise', 'tq_sight', 'tq_walking', 'tq_vomiting', 'tq_sudden_death'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      Worms: {
        questions:  ['tq_eating', 'tq_swollen', 'tq_hair_loss', 'tq_diarrhea'],
        thresholds: { MEDIUM: 2, HIGH: 3 },
      },
      Mange: {
        questions:  ['tq_skin', 'tq_hair_loss'],
        thresholds: { MEDIUM: 1, HIGH: 2 },
      },
    },

  },

  scoring: {
    tq_eating: {
      not_eating: 1,
      eats_less:  0.5,
      normal:     0,
    },
    tq_urine_color: {
      bloody:     1,
      very_dark:  1,
      colourless: 0.5,
      normal:     0,
    },
    tq_walk_type: {
      circles:     1,
      stumbling:   1,
      not_walking: 1,
      straight:    0,
    },
    tq_stool: {
      bloody: 1,
      watery: 1,
      hard:   0,
      normal: 0,
    },
    tq_secretion_type: {
      blood:  1,
      pus:    1,
      froth:  0.5,
      mucus:  0.5,
    },
    tq_milk: {
      stopped:   1,
      different: 1,
      less:      0.5,
      normal:    0,
    },
    tq_eggs: {
      stopped: 1,
      less:    0.5,
      normal:  0,
    },
    // Reversed yes/no: reproductive failure scores 1 (animal did NOT reproduce successfully)
    tq_reproduction: {
      yes: 0,
      no:  1,
    },
  },

  optionLabels: {
    english: {
      not_eating:  'Not eating at all',
      eats_less:   'Eats less than usual',
      normal:      'Normal',
      bloody:      'Bloody or red',
      very_dark:   'Very dark',
      colourless:  'Colourless or watery',
      circles:     'In circles',
      stumbling:   'Stumbling or drunk-like',
      not_walking: 'Not walking at all',
      straight:    'Straight / normally',
      watery:      'Watery or loose',
      hard:        'Hard or pellet-like',
      blood:       'Blood',
      pus:         'Pus',
      froth:       'Froth or saliva',
      mucus:       'Mucus',
      stopped:     'Stopped completely',
      different:   'Looks different',
      less:        'Less than usual',
    },
    runyankole: {
      not_eating:  '[PLACEHOLDER]',
      eats_less:   '[PLACEHOLDER]',
      normal:      '[PLACEHOLDER]',
      bloody:      '[PLACEHOLDER]',
      very_dark:   '[PLACEHOLDER]',
      colourless:  '[PLACEHOLDER]',
      circles:     '[PLACEHOLDER]',
      stumbling:   '[PLACEHOLDER]',
      not_walking: '[PLACEHOLDER]',
      straight:    '[PLACEHOLDER]',
      watery:      '[PLACEHOLDER]',
      hard:        '[PLACEHOLDER]',
      blood:       '[PLACEHOLDER]',
      pus:         '[PLACEHOLDER]',
      froth:       '[PLACEHOLDER]',
      mucus:       '[PLACEHOLDER]',
      stopped:     '[PLACEHOLDER]',
      different:   '[PLACEHOLDER]',
      less:        '[PLACEHOLDER]',
    },
    acholi: {
      not_eating:  '[PLACEHOLDER]',
      eats_less:   '[PLACEHOLDER]',
      normal:      '[PLACEHOLDER]',
      bloody:      '[PLACEHOLDER]',
      very_dark:   '[PLACEHOLDER]',
      colourless:  '[PLACEHOLDER]',
      circles:     '[PLACEHOLDER]',
      stumbling:   '[PLACEHOLDER]',
      not_walking: '[PLACEHOLDER]',
      straight:    '[PLACEHOLDER]',
      watery:      '[PLACEHOLDER]',
      hard:        '[PLACEHOLDER]',
      blood:       '[PLACEHOLDER]',
      pus:         '[PLACEHOLDER]',
      froth:       '[PLACEHOLDER]',
      mucus:       '[PLACEHOLDER]',
      stopped:     '[PLACEHOLDER]',
      different:   '[PLACEHOLDER]',
      less:        '[PLACEHOLDER]',
    },
  },

};
